version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: uv
    directory: /worker
    schedule:
      interval: weekly
