name: Gitleaks

on:
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    name: Secret Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required to post annotations on PRs
      pull-requests: read

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
