name: OAuth Worker

on:
  pull_request:
    branches:
    - main
    paths:
      - worker/**
      - .github/workflows/oauth-worker.yml

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Run tests
        run: uv run python -m pytest tests/ -v
        working-directory: worker
